# Generated by Django 5.1.3 on 2024-12-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cur_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_date', models.DateField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.paper')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='papers_list',
            field=models.ManyToManyField(through='wallet.PortfolioPaper', to='wallet.paper'),
        ),
    ]
